# Generated by Django 2.2.17 on 2021-04-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.Student'),
        ),
    ]
