# Generated by Django 2.2.17 on 2021-04-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20210423_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Student'),
        ),
    ]
