# Generated by Django 2.2.17 on 2021-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_auto_20210423_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sem',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='Course', to='Management.Teacher'),
        ),
    ]
