# Generated by Django 2.2.17 on 2021-04-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20210423_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Student'),
        ),
    ]
