# Generated by Django 2.2.17 on 2021-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20210423_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, choices=[('y', 1), ('e', 2), ('a', 3), ('r', 4)], default='y', help_text='Select Year', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Enter Subject for this course e.g. DSA', max_length=64),
        ),
    ]
