# Generated by Django 2.2.17 on 2021-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20210424_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='one', help_text='Please Select Semester', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('y', 1), ('e', 2), ('a', 3), ('r', 4)], default='y', help_text='Select Year', max_length=1),
        ),
    ]
