# Generated by Django 2.2.17 on 2021-04-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20210424_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(null=True, to='Management.Student'),
        ),
    ]
