# Generated by Django 2.2.17 on 2021-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_auto_20210424_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
