# Generated by Django 2.2.17 on 2021-04-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_auto_20210424_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(blank=True, choices=[('y', 1), ('e', 2), ('a', 3), ('r', 4)], default='y', help_text='Select year for Class', max_length=1),
        ),
    ]
