# Generated by Django 2.2.17 on 2021-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_auto_20210424_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='y', help_text='Select year for Class', max_length=1),
        ),
    ]
