# Generated by Django 2.2.17 on 2021-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0021_auto_20210424_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='Subject', to='Management.Teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='y', help_text='Select Year', max_length=1),
        ),
    ]
