# Generated by Django 2.2.17 on 2021-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0022_auto_20210424_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(null=True, to='Management.Subject'),
        ),
    ]
