# Generated by Django 2.2.17 on 2021-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0025_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='1', help_text='Select Semester', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', help_text='Select Year', max_length=1),
        ),
    ]
