# Generated by Django 2.2.17 on 2021-04-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0026_auto_20210427_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject',
            new_name='subjects',
        ),
    ]
