# Generated by Django 2.2.17 on 2021-04-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0027_auto_20210427_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', help_text='Select year for course', max_length=1, null=True),
        ),
    ]
