# Generated by Django 2.2.17 on 2021-05-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0028_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(help_text='Select Course for this class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Management.Course'),
        ),
    ]
