# Generated by Django 2.2.17 on 2021-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0029_auto_20210503_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='admitYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='className',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='collegeName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='professionalName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='studentName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student Roll No.', max_length=64),
        ),
    ]
