# Generated by Django 2.2.17 on 2021-05-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0030_auto_20210511_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='homeAddress',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='postCode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
