# Generated by Django 2.2.17 on 2021-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0034_auto_20210512_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('courseNumber', models.CharField(max_length=64, null=True)),
                ('knowledgePoint', models.CharField(max_length=64, null=True)),
                ('chapterSection', models.CharField(max_length=64, null=True)),
                ('testQuestionType', models.CharField(max_length=10, null=True)),
                ('titleName', models.CharField(max_length=50, null=True)),
                ('testQuestionContent', models.CharField(max_length=200, null=True)),
                ('testQuestionAnwser', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
