# Generated by Django 2.2.17 on 2021-05-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0036_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherNumber', models.CharField(max_length=64, null=True)),
                ('problemNumber', models.CharField(max_length=64, null=True)),
                ('answerTime', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(max_length=64, null=True)),
                ('courseNumber', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(max_length=64, null=True)),
                ('problemNumber', models.CharField(max_length=64, null=True)),
                ('proposedTime', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=64, null=True)),
                ('teacherNumber', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNumber', models.CharField(max_length=64, null=True)),
                ('userName', models.CharField(max_length=64, null=True)),
                ('loginPassword', models.CharField(max_length=64, null=True)),
                ('roleNumber', models.CharField(max_length=64, null=True)),
                ('roleName', models.CharField(max_length=64, null=True)),
                ('passwordProblem', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
