# Generated by Django 2.2.17 on 2021-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0037_answer_electives_proposed_teach_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='experimentHours',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='theoreticalHours',
            field=models.SmallIntegerField(null=True),
        ),
    ]
