# Generated by Django 2.2.17 on 2021-05-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0038_auto_20210521_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.ManyToManyField(null=True, to='Management.Course')),
                ('studentNumber', models.ManyToManyField(null=True, to='Management.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='Electives',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='problemNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Problem'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='teacherNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Teacher'),
        ),
        migrations.AlterField(
            model_name='proposed',
            name='problemNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Problem'),
        ),
        migrations.AlterField(
            model_name='proposed',
            name='proposedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proposed',
            name='studentNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.Student'),
        ),
        migrations.RemoveField(
            model_name='teach',
            name='courseNumber',
        ),
        migrations.AddField(
            model_name='teach',
            name='courseNumber',
            field=models.ManyToManyField(null=True, to='Management.Course'),
        ),
        migrations.RemoveField(
            model_name='teach',
            name='teacherNumber',
        ),
        migrations.AddField(
            model_name='teach',
            name='teacherNumber',
            field=models.ManyToManyField(null=True, to='Management.Teacher'),
        ),
    ]
