# Generated by Django 2.2.17 on 2021-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0041_auto_20210527_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin')], default='student', help_text='Please select this Correctly, Because you will be Checked.', max_length=20, null=True),
        ),
    ]
